"""Create initial tables.

Revision ID: 1b0a39810809
Revises: 7ee23714e4e3
Create Date: 2024-02-13 15:21:40.662701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b0a39810809'
down_revision = '7ee23714e4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], name=op.f('fk_user_sessions_user_id_user_auth')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('openai_interactions')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.Integer(), nullable=True))
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_chat_messages_session_id_user_sessions'), 'user_sessions', ['session_id'], ['id'])

    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.drop_constraint('user_auth_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_auth', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_auth_email_key', ['email'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_messages_session_id_user_sessions'), type_='foreignkey')
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('session_id')

    op.create_table('openai_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_auth.id'], name='fk_openai_interactions_user_id_user_auth'),
    sa.PrimaryKeyConstraint('id', name='openai_interactions_pkey')
    )
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
