"""initial migration

Revision ID: 78f6da466abe
Revises: daa5f641d60b
Create Date: 2024-02-02 13:27:27.878018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f6da466abe'
down_revision = 'daa5f641d60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('confirmation_num', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'orders', ['confirmation_num'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'confirmation_num')
    # ### end Alembic commands ###
