"""initial migration

Revision ID: 7ee23714e4e3
Revises: b73dd5fcfd58
Create Date: 2024-02-07 17:03:34.522805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee23714e4e3'
down_revision = 'b73dd5fcfd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shipping_info_user_id_user_auth', 'shipping_info', type_='foreignkey')
    op.drop_column('shipping_info', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_info', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key('fk_shipping_info_user_id_user_auth', 'shipping_info', 'user_auth', ['user_id'], ['id'])
    # ### end Alembic commands ###
